# Generated by Django 3.1.4 on 2020-12-21 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diretor',
            options={'verbose_name_plural': 'Diretores'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('PF', 'perfumaria'), ('SM', 'similar'), ('GN', 'generico'), ('ET', 'etico')], default='ET', max_length=2),
        ),
    ]
