# Generated by Django 3.1.4 on 2020-12-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20201221_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='encomenda',
            field=models.CharField(default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='pedido',
            name='falta',
            field=models.CharField(default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Perfumaria'), ('SM', 'Similar'), ('GN', 'Genérico'), ('ET', 'Ético')], default='ET', max_length=2),
        ),
    ]
