# Generated by Django 3.1.4 on 2020-12-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20201221_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='falta',
            field=models.CharField(default='nao', max_length=3),
        ),
    ]
