# Generated by Django 3.1.4 on 2020-12-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20201221_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descricao',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='encomenda',
            field=models.CharField(blank=True, default='nao', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='falta',
            field=models.CharField(blank=True, default='nao', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.CharField(max_length=25),
        ),
    ]
