# Generated by Django 3.1.4 on 2020-12-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20201221_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descricao',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='marca',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
